language: node_js
sudo: true
node_js:
  - v6

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest

script:
  - npm test

cache:
  directories:
    - "node__modules"