language: node_js
sudo: true
node_js:
  - v6

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest

addons:
  sonarcloud:
    organization: "snayerman-github"
    token:
      secure: "b0ed055747bb5c3379c3d2f3aa3da50b841d9d20"

script:
  - npm test
  - sonar-scanner

cache:
  directories:
    - "node__modules"
    - '$HOME/.sonar/cache'